### ISSUE TITLE
[Фильтр] Правки

### ISSUE THREAD

**Issue by ixax** [ixax/fl-buket#57]
- [x] У всех контролов фильтров должно быть API
- [x] При смене состояния любых контролов менять урл
- [x] На страницах `events` у кнопок «размеры», «цена», «фильтр» нет рамок и меняется подложка (см. [макет](http://jobs.silverplate.ru/buket74/?catalog#10))
- [x] При наведении на «размеры», «цена» некорректный цвет фона кнопки (см. [макет](http://jobs.silverplate.ru/buket74/?catalog#2))
- [x] [Кнопки имеют разную высоту](https://drive.google.com/file/d/0B8O4jn0E_cvKVmJtWUJHNTZUMnc/edit?usp=drivesdk)
- [x] Кнопка «Вернуть»
- [x] Кнопка «Сбросить»
- [x] Враппер с тегами должен иметь минимальную высоту равную высоте и отступам самого тега
- [x] [Фильтры на странице событий поехали](https://drive.google.com/file/d/0B8O4jn0E_cvKTFQ5eHpBOE9uU2c/edit?usp=drivesdk)
- [x] [В каталоге фильтры не в ряд](https://drive.google.com/file/d/0B8O4jn0E_cvKeV9MWHV4bEFyTU0/edit?usp=drivesdk)
- [x] Оптимизировать пространство в фильтрах «размеры», «цена», «фильтр». В идеале одна строка, в мобилках допустимо две, но можно попробовать убрать текст «Фильтр и оставить иконку». [Оригинальная задача](https://github.com/ixax/fl-buket/issues/32)

**Comment by drdim** [comment]
В каком формате работаем с галками?

**Comment by ixax** [comment]
> В каком формате работаем с галками?

Не понял?

**Comment by ixax** [comment]
@drdim Что делает кнопка «Вернуть»?

**Comment by ixax** [comment]
@drdim Без кнопок тут все, можно смотреть.
И можно написать ТЗ на эти кнопки :)

**Comment by drdim** [comment]
Кнопка вернуть возвращает состояние фильтров до нажатия на кнопку сбросить.

16 июля 2015 г., 15:41 пользователь Viacheslav Glushko <
notifications@github.com> написал:

**Comment by drdim** [comment]
т.е. ссылка с иконкой сбросить - скидывает фильтр, а вернуть с иконкой
возврата - возвращает предыдущее состояние фильтра.


16 июля 2015 г., 16:46 пользователь Богаткин Дмитрий <dr.dim.pro@gmail.com>
написал:

**Comment by drdim** [comment]
Еще я не вижу кнопки сбросить.

**Comment by ixax** [comment]
Потому что ТЗ было непонятно, верну.
