### ISSUE TITLE
Каталог. Нет разделов, недостающий функционал.

### ISSUE THREAD

**Issue by drdim** [ixax/fl-buket#97]
- [x] Композиции - http://ixax.github.io/fl-buket/composition.html Выдает 404.http://jobs.silverplate.ru/buket74/?catalog#12 - другой баннер
- [x] Монобукеты http://ixax.github.io/fl-buket/monobuket.html 404 http://jobs.silverplate.ru/buket74/?catalog#10 - другой баннер
- [x] События http://jobs.silverplate.ru/buket74/?catalog#11 - другой баннер
- [x] Нет механики догрузки букетов при прокрутке, данный блок находится внизу, догружает при клике еще 9 товаров (можно для примера те же грузить, главное, чтобы код работал) Если догружать больше нечего скрывать эту прокрутку. https://drive.google.com/file/d/0B8O4jn0E_cvKai1jeGI1RnpPUlk/view?usp=drivesdk
- [x] Сделать побольше логотип (https://drive.google.com/file/d/0B8O4jn0E_cvKcksxejhWUG1ZZW8/view?usp=drivesdk)
в оригинале высота 267 сделать такой же. (Пробовал хорошо вписывается и уже текст читается)

**Comment by ixax** [comment]
**1, 2 пункты**
Абсолютно идентичны со страницей events, сделаю дублирование

**1, 2, 3 — баннеры**
У меня нет исходников этих страниц, делалось с картинок на silverplate, соответственно баннер взялся с главной. Поменять его вообще элементарно и конечно это предусмотрено.

**4-й пункт**
Сделал прелоадер, механика не реализована потому что её не обсуждали, это пойдет доп. функционалом, но сделаю сейчас, ок

Логотип увеличу

**Comment by drdim** [comment]
>1, 2 пункты
>Абсолютно идентичны со страницей events, сделаю дублирование

Разные баннеры только, и нет кнопок.

Если нет картинок, забить на это.

**Comment by ixax** [comment]
Здесь всё
